In [15]:
import pandas as pd
import time

import googlemaps
import json
from haversine import haversine

from sklearn import preprocessing

import folium
import webbrowser
import os

In [16]:
#데이터프레임 불러오기
# import pandas as pd

df = pd.read_csv("꽉찬전국도서관표준데이터-20201223.csv", index_col=0, encoding='utf-8')
columns = ['도서관명', '도서관유형', '열람좌석수', '자료수', '건물면적', '위도', '경도', '좌표']
df = df[columns]

In [17]:
choice_ex = ["열람좌석수", "건물면적", "자료수"]

def user_preference():
    
    print("-----아래의 목록에서 골라주세요-----") 
    print(choice_ex)
    print("------------------------------------")
        
    while len(choice_ex) == 3:
        point1 = input("1순위 : ")
        if point1 not in choice_ex:
            print("입력이 잘못되었습니다. 다시 입력해주세요")
            continue
        else:
            choice_ex.remove(point1)
            
    while len(choice_ex) == 2:
        point2 = input("2순위 : ")
        if point2 not in choice_ex:
            print("입력이 잘못되었습니다. 다시 입력해주세요")
            continue
        else:
            choice_ex.remove(point2)
            
    point3 = choice_ex[0]
                       
    print("3순위 : " + point3)
    return point1 , point2 , point3

In [18]:
# import time

point1 , point2 , point3 = user_preference()

time.sleep(1)
print()
print("검색하고 싶은 장소를 입력해주세요! ex) 선릉역.")

loc = input("위치 입력 : ")

-----아래의 목록에서 골라주세요-----
['열람좌석수', '건물면적', '자료수']
------------------------------------
1순위 : 열람좌석수
2순위 : 자료수
3순위 : 건물면적

검색하고 싶은 장소를 입력해주세요! ex) 선릉역.
위치 입력 : 선릉역

In [19]:
# import googlemaps
# import json
# from haversine import haversine

#'거리' 구하기 밑작업
df['거리'] = 0.00

#Google Map API 접속
gmaps_key = "AIzaSyDhbMWTY9Zs3z2AA8Z_c05j2oUPfdhUd0c"
gmaps = googlemaps.Client(key = gmaps_key)

#좌표값 받는 함수
def user_location(user_loc): 
    while True :
        tmp = gmaps.geocode(user_loc) #주소로 검색해 좌표로 돌려주는 API기능
        if bool(tmp) : #검색이 된다면
            tmp_loc = tmp[0].get('geometry')
            lat = tmp_loc['location']['lat']
            lng = tmp_loc['location']['lng']
            if ((lat > 0) & (lng > 0)): #검색성공
                return lat, lng
        else:
            print('정확한 도로명 주소를 남겨주세요')
            user_loc = input("위치 입력 : ")
            continue

In [20]:
#입력받은 위치 기반 '거리' 열 구하기
location = loc
loc1 = user_location(location)
df['거리'] = df.apply(lambda row: haversine(loc1, (row['위도'], row['경도'])), axis = 1)
#처리 시간을 줄이기 위한 apply 함수 활용

In [21]:
#가까운 도서관 상위 10개 뽑기
df_top = df.sort_values(by='거리', axis=0).head(10)
df_top

,도서관명,도서관유형,열람좌석수,자료수,건물면적,위도,경도,좌표,거리
414,즐거운도서관,공공도서관,94,36254,325.00,37.499729,127.057847,"37.499728838, 127.05784739",0.946042
401,역삼2동작은도서관,작은도서관,18,12136,121.92,37.495892,127.046477,"37.495891968, 127.04647729",0.980440
415,행복한도서관,공공도서관,142,42986,434.00,37.502306,127.064187,"37.502306044, 127.06418712",1.365206
400,대치1작은도서관,작은도서관,26,20291,73.00,37.493246,127.056775,"37.493245715, 127.05677492",1.427621
413,대치도서관,공공도서관,143,54800,580.00,37.499616,127.065917,"37.49961649, 127.06591734",1.591153
389,삼성도서관,작은도서관,64,22528,96.00,37.514355,127.062609,"37.514355126, 127.06260935",1.629165
411,정다운도서관,공공도서관,66,45417,307.00,37.519098,127.046442,"37.519098264, 127.0464419",1.639776
417,역삼도서관,공공도서관,115,33824,396.00,37.495374,127.033282,"37.495373838, 127.03328248",1.714317
416,역삼푸른솔도서관,공공도서관,134,37263,568.00,37.496499,127.032030,"37.49649864, 127.03203001",1.737463
410,논현도서관,공공도서관,190,44920,450.00,37.517278,127.037204,"37.517277909, 127.03720420479999",1.759980

In [22]:
#정규화
org_columns = ['도서관명', '위도', '경도', '열람좌석수', '자료수'] #위도와 경도의 정규화방지를 위해 필요한 열만 넣어서 데이터프레임을 따로복사
df_org = df_top[org_columns]
columns = ['도서관명', '열람좌석수', '자료수', '건물면적', '거리']
df_top = df_top[columns]

df_top.set_index('도서관명', inplace=True) #두개 다 인덱스를 도서관명으로 지정
df_org.set_index('도서관명', inplace=True)

#정규화를 위해 데이터프레임 잠시 분리
df_top_dist = df_top['거리']

df_top_nodist = df_top.copy(deep=True)
del df_top_nodist['거리']

In [23]:
# from sklearn import preprocessing

# Min-Max 정규화
scaler = preprocessing.MinMaxScaler()
scaler.fit(df_top_nodist)
df_top_norm = scaler.transform(df_top_nodist)

# 정규화값 결정하기
df_top_norm = pd.DataFrame(df_top_norm)
df_top_norm.index = df_top_nodist.index
df_top_norm.columns = df_top_nodist.columns
df_top_norm['거리'] = df_top_dist
df_top_norm

C:\Users\Daechung\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

              열람좌석수       자료수      건물면적        거리
도서관명
즐거운도서관     0.441860  0.565301  0.497041  0.946042
역삼2동작은도서관  0.000000  0.000000  0.096489  0.980440
행복한도서관     0.720930  0.723092  0.712032  1.365206
대치1작은도서관   0.046512  0.191145  0.000000  1.427621
대치도서관      0.726744  1.000000  1.000000  1.591153
삼성도서관      0.267442  0.243578  0.045365  1.629165
정다운도서관     0.279070  0.780072  0.461538  1.639776
역삼도서관      0.563953  0.508344  0.637081  1.714317
역삼푸른솔도서관   0.674419  0.588951  0.976331  1.737463
논현도서관      1.000000  0.768423  0.743590  1.759980

In [24]:
#점수 내기
df_top_norm['score'] = (df_top_norm[point1] * 6) \
                        + (df_top_norm[point2] * 3) \
                        + (df_top_norm[point3] * 1)
df_top_norm['score'] = df_top_norm['score']
df_top_norm

              열람좌석수       자료수      건물면적        거리     score
도서관명
즐거운도서관     0.441860  0.565301  0.497041  0.946042  4.844107
역삼2동작은도서관  0.000000  0.000000  0.096489  0.980440  0.096489
행복한도서관     0.720930  0.723092  0.712032  1.365206  7.206889
대치1작은도서관   0.046512  0.191145  0.000000  1.427621  0.852504
대치도서관      0.726744  1.000000  1.000000  1.591153  8.360465
삼성도서관      0.267442  0.243578  0.045365  1.629165  2.380749
정다운도서관     0.279070  0.780072  0.461538  1.639776  4.476174
역삼도서관      0.563953  0.508344  0.637081  1.714317  5.545835
역삼푸른솔도서관   0.674419  0.588951  0.976331  1.737463  6.789696
논현도서관      1.000000  0.768423  0.743590  1.759980  9.048859

In [25]:
#현재까지는 정렬구조가 같으므로 기존 복사해둔 df_org에서 위도와 경도 열을 가져와서 그대로 넣어줌(score 기준으로 정렬하기전에) 
for name in df_org:
    df_top_norm["위도"] = df_org["위도"]
    df_top_norm["경도"] = df_org["경도"]
    df_top_norm["자료수(원본)"] = df_org["자료수"]
    df_top_norm["열람좌석수(원본)"] = df_org["열람좌석수"]

In [26]:
#최종 데이터프레임
df_top_norm = df_top_norm.sort_values(by="score",ascending=False)
df_top_norm

,열람좌석수,자료수,건물면적,거리,score,위도,경도,자료수(원본),열람좌석수(원본)
도서관명,,,,,,,,,
논현도서관,1.000000,0.768423,0.743590,1.759980,9.048859,37.517278,127.037204,44920,190
대치도서관,0.726744,1.000000,1.000000,1.591153,8.360465,37.499616,127.065917,54800,143
행복한도서관,0.720930,0.723092,0.712032,1.365206,7.206889,37.502306,127.064187,42986,142
역삼푸른솔도서관,0.674419,0.588951,0.976331,1.737463,6.789696,37.496499,127.032030,37263,134
역삼도서관,0.563953,0.508344,0.637081,1.714317,5.545835,37.495374,127.033282,33824,115
즐거운도서관,0.441860,0.565301,0.497041,0.946042,4.844107,37.499729,127.057847,36254,94
정다운도서관,0.279070,0.780072,0.461538,1.639776,4.476174,37.519098,127.046442,45417,66
삼성도서관,0.267442,0.243578,0.045365,1.629165,2.380749,37.514355,127.062609,22528,64
대치1작은도서관,0.046512,0.191145,0.000000,1.427621,0.852504,37.493246,127.056775,20291,26
역삼2동작은도서관,0.000000,0.000000,0.096489,0.980440,0.096489,37.495892,127.046477,12136,18

In [27]:
#지도 시각화
# import folium

n_list = []
m_number_list = []
s_number_list = []


map = folium.Map(location=loc1, zoom_start=14)


for i , n in enumerate(df_top_norm.index):
    n_list.append(n)
    m_number_list.append(df_top_norm['자료수(원본)'][n])
    s_number_list.append(df_top_norm['열람좌석수(원본)'][n])
    
    # 1등
    if i == 0 : 
        folium.Marker([df_top_norm['위도'][n], df_top_norm['경도'][n]], 
                  popup = "추천순위 : " + str(i+1)
                  + "<br>도서관명 : " + n
                  + "<br>자료수 : " + str(df_top_norm['자료수(원본)'][n]) 
                  + "<br>열람좌석수 : " + str(df_top_norm['열람좌석수(원본)'][n]), 
                  icon= (folium.Icon(icon="book", prefix="fa", color="red"))).add_to(map)
    # 2~4등
    elif i <= 3 :
        folium.Marker([df_top_norm['위도'][n], df_top_norm['경도'][n]], 
                  popup = "추천순위 : " + str(i+1)
                  + "<br>도서관명 : " + n
                  + "<br>자료수 : " + str(df_top_norm['자료수(원본)'][n]) 
                  + "<br>열람좌석수 : " + str(df_top_norm['열람좌석수(원본)'][n]), 
                  icon= (folium.Icon(icon="book", prefix="fa", color="blue"))).add_to(map)
    # 5~10등
    else :
        folium.Marker([df_top_norm['위도'][n], df_top_norm['경도'][n]], 
                  popup = "추천순위 : " + str(i+1)
                  + "<br>도서관명 : " + n
                  + "<br>자료수 : " + str(df_top_norm['자료수(원본)'][n]) 
                  + "<br>열람좌석수 : " + str(df_top_norm['열람좌석수(원본)'][n]), 
                  icon= (folium.Icon(icon="book", prefix="fa", color="green"))).add_to(map)
                  
    
    map.save('map.html')

In [28]:
# import webbrowser
# import os

print("6팀 추천 당신에게 딱 맞는 도서관 : {}.".format(df_top_norm.index[0]))

print()
print("5초 후 map이 자동으로 열립니다")

for x in reversed(range(5)):
    print(x + 1)
    time.sleep(1)
webbrowser.open('file://' + os.path.realpath("./map.html"))

6팀 추천 당신에게 딱 맞는 도서관 : 논현도서관.

5초 후 map이 자동으로 열립니다
5
4
3
2
1

True